refactor: don't run on Windows

diff --git a/chezmoi-tmpl b/chezmoi-tmpl
--- a/chezmoi-tmpl
+++ b/chezmoi-tmpl
@@ -11,13 +11,17 @@ die() {
 }
 
 # Check pre-requisites
-jq --version >/dev/null 2>&1 || {
-    die f "jq is required. Please install it, then try again."
+if [[ $(chezmoi data | jq --raw-output '.chezmoi.os') == "windows" ]]; then
+    die f "Windows is not supported yet."
+    exit 1
+fi
+[[ ${BASH_VERSINFO[0]} -gt 3 ]] || {
+    die f "Bash version 4 or newer is required. Current version: $BASH_VERSION"
     exit 1
 }
 
-[[ ${BASH_VERSINFO[0]} -gt 3 ]] || {
-    die f "Bash version 4 or newer is required. Current version: $BASH_VERSION"
+jq --version >/dev/null 2>&1 || {
+    die f "jq is required. Please install it, then try again."
     exit 1
 }
 
